-- =============================================================
-- CDGS — Phase 3 & 4 Migration: Change Detection Pipeline & Stage Logs
-- Run AFTER 002 (002_phase2_auth.sql) in Supabase SQL Editor.
-- =============================================================

BEGIN;

-- =============================================================
-- 1. pipeline_runs
--    Pipeline execution records for Phase 3 change detection.
-- =============================================================
CREATE TABLE IF NOT EXISTS pipeline_runs (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  repository_id   UUID        NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
  triggered_by    UUID        REFERENCES users(id) ON DELETE SET NULL,
  trigger_type    TEXT        NOT NULL DEFAULT 'webhook' CHECK (trigger_type IN ('webhook', 'manual', 'scheduled')),
  commit_sha      TEXT        NOT NULL, -- NOTE: Represents afterSha (the new commit head), not beforeSha
  before_sha      TEXT,
  branch          TEXT        NOT NULL DEFAULT 'main',
  status          TEXT        NOT NULL DEFAULT 'queued'
                              CHECK (status IN ('queued', 'running', 'success', 'failed', 'retrying')),
  current_stage   TEXT        NOT NULL DEFAULT 'webhook'
                              CHECK (current_stage IN ('webhook', 'clone', 'diff', 'docgen', 'ai', 'publish')),
  queued_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  started_at      TIMESTAMPTZ,
  finished_at     TIMESTAMPTZ,
  duration_ms     INTEGER,
  error_message   TEXT,
  retry_count     INTEGER     NOT NULL DEFAULT 0,
  changeset       JSONB,      -- Persisted ChangeSet JSONB object (Phase 3)
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Idempotency constraint: Prevent duplicate runs for the same commit on the same branch
  CONSTRAINT pipeline_runs_repo_commit_branch_unique UNIQUE (repository_id, commit_sha, branch)
);

COMMENT ON TABLE pipeline_runs IS 'Tracks Phase 3 change detection and Phase 4 documentation pipeline executions';
COMMENT ON COLUMN pipeline_runs.commit_sha IS 'Represents afterSha (the new commit head), not beforeSha';
COMMENT ON COLUMN pipeline_runs.changeset IS 'Persisted ChangeSet JSONB output from Phase 3 git diff';

-- =============================================================
-- 2. pipeline_stage_logs
--    Granular stage timing and transition logs per run.
-- =============================================================
CREATE TABLE IF NOT EXISTS pipeline_stage_logs (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id        UUID        NOT NULL REFERENCES pipeline_runs(id) ON DELETE CASCADE,
  stage         TEXT        NOT NULL CHECK (stage IN ('webhook', 'clone', 'diff', 'docgen', 'ai', 'publish')),
  status        TEXT        NOT NULL CHECK (status IN ('queued', 'running', 'success', 'failed', 'retrying')),
  started_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  finished_at   TIMESTAMPTZ,
  duration_ms   INTEGER,
  error_message TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE pipeline_stage_logs IS 'Granular stage timing and status logs for each pipeline run (Phase 3 & 4)';

-- =============================================================
-- 3. documentation_versions
--    Versioned documentation snapshots generated by Phase 4.
-- =============================================================
CREATE TABLE IF NOT EXISTS documentation_versions (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id          UUID        NOT NULL REFERENCES pipeline_runs(id) ON DELETE CASCADE,
  repository_id   UUID        NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
  version_number  INTEGER     NOT NULL DEFAULT 1,
  commit_sha      TEXT        NOT NULL,
  is_published    BOOLEAN     NOT NULL DEFAULT true,
  published_at    TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT documentation_versions_repo_version_unique UNIQUE (repository_id, version_number)
);

COMMENT ON TABLE documentation_versions IS 'Versioned documentation snapshots produced by Phase 4 docgen engine';

-- =============================================================
-- 4. documents
--    Individual generated documentation artifacts per version.
-- =============================================================
CREATE TABLE IF NOT EXISTS documents (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  version_id      UUID        NOT NULL REFERENCES documentation_versions(id) ON DELETE CASCADE,
  repository_id   UUID        NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
  file_path       TEXT        NOT NULL,
  doc_type        TEXT        NOT NULL CHECK (doc_type IN ('readme', 'api', 'module', 'function', 'class', 'other')),
  title           TEXT        NOT NULL,
  content         TEXT        NOT NULL,
  content_hash    TEXT        NOT NULL,
  ai_model        TEXT,
  token_count     INTEGER     DEFAULT 0,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE documents IS 'Individual generated documentation files (Swagger, JSDoc, MkDocs) per Phase 4 version';

-- =============================================================
-- Indexes
-- =============================================================
CREATE INDEX IF NOT EXISTS idx_pipeline_runs_repo_id     ON pipeline_runs(repository_id);
CREATE INDEX IF NOT EXISTS idx_pipeline_runs_status      ON pipeline_runs(status);
CREATE INDEX IF NOT EXISTS idx_pipeline_runs_created_at  ON pipeline_runs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_stage_logs_run_id         ON pipeline_stage_logs(run_id);
CREATE INDEX IF NOT EXISTS idx_doc_versions_repo_id      ON documentation_versions(repository_id);
CREATE INDEX IF NOT EXISTS idx_doc_versions_run_id       ON documentation_versions(run_id);
CREATE INDEX IF NOT EXISTS idx_documents_version_id      ON documents(version_id);
CREATE INDEX IF NOT EXISTS idx_documents_repo_id         ON documents(repository_id);

-- =============================================================
-- Auto-update trigger for pipeline_runs.updated_at
-- =============================================================
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'trigger_set_updated_at') THEN
    CREATE OR REPLACE TRIGGER trg_pipeline_runs_updated_at
      BEFORE UPDATE ON pipeline_runs
      FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();
  END IF;
END;
$$;

-- =============================================================
-- Alter existing tables if migration 003 was already applied
-- (Safe idempotent ALTER for teams who already ran old 003)
-- =============================================================
DO $$
BEGIN
  -- Add docgen/ai/publish to pipeline_runs.current_stage constraint if needed
  IF EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'pipeline_runs_current_stage_check'
    AND table_name = 'pipeline_runs'
  ) THEN
    ALTER TABLE pipeline_runs DROP CONSTRAINT IF EXISTS pipeline_runs_current_stage_check;
    ALTER TABLE pipeline_runs
      ADD CONSTRAINT pipeline_runs_current_stage_check
      CHECK (current_stage IN ('webhook', 'clone', 'diff', 'docgen', 'ai', 'publish'));
  END IF;

  -- Add docgen/ai/publish to pipeline_stage_logs.stage constraint if needed
  IF EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'pipeline_stage_logs_stage_check'
    AND table_name = 'pipeline_stage_logs'
  ) THEN
    ALTER TABLE pipeline_stage_logs DROP CONSTRAINT IF EXISTS pipeline_stage_logs_stage_check;
    ALTER TABLE pipeline_stage_logs
      ADD CONSTRAINT pipeline_stage_logs_stage_check
      CHECK (stage IN ('webhook', 'clone', 'diff', 'docgen', 'ai', 'publish'));
  END IF;
END;
$$;

COMMIT;
