import type { ParsedCodeFile, GeneratedDocument } from './docgen.types'
import { computeContentHash } from './parser.service'

/**
 * Generates API and Code Module reference documentation in Markdown format.
 */
export function generateJSDocDoc(
  parsedFiles: ParsedCodeFile[],
): GeneratedDocument[] {
  const documents: GeneratedDocument[] = []

  for (const file of parsedFiles) {
    if (file.symbols.length === 0) continue

    const lines: string[] = [
      `# Module: \`${file.filePath}\``,
      '',
      `**Language**: ${file.language}`,
      `**Exported Symbols**: ${file.symbols.length}`,
      '',
      '| Symbol Name | Kind | Description |',
      '|---|---|---|',
    ]

    for (const sym of file.symbols) {
      lines.push(`| \`${sym.name}\` | \`${sym.kind}\` | Exported ${sym.kind} symbol |`)
    }

    lines.push('', '---', '*Generated by CDGS Automatic Documentation Engine.*')

    const content = lines.join('\n')
    const docPath = `docs/api/${file.filePath.replace(/[/\\.]/g, '_')}.md`

    documents.push({
      filePath: docPath,
      docType: file.symbols.some((s) => s.kind === 'route') ? 'api' : 'module',
      title: `API Reference: ${file.filePath}`,
      content,
      contentHash: computeContentHash(content),
    })
  }

  return documents
}
