import type { ParsedCodeFile, GeneratedDocument } from './docgen.types'
import { computeContentHash } from './parser.service'

/**
 * Generates/updates OpenAPI 3.0 specification documentation artifact.
 */
export function generateSwaggerDoc(
  repoName: string,
  parsedFiles: ParsedCodeFile[],
): GeneratedDocument | null {
  const routes = parsedFiles.flatMap((f) => f.symbols.filter((s) => s.kind === 'route'))

  if (routes.length === 0 && !parsedFiles.some((f) => f.hasSwaggerAnnotations)) {
    return null
  }

  const paths: Record<string, any> = {}

  for (const route of routes) {
    const parts = route.name.split(' ')
    const method = (parts[0] || 'GET').toLowerCase()
    const pathUrl = parts[1] || '/'

    if (!paths[pathUrl]) paths[pathUrl] = {}
    paths[pathUrl][method] = {
      summary: `Automated route: ${route.name}`,
      responses: {
        '200': { description: 'Success' },
      },
    }
  }

  const openApiSpec = {
    openapi: '3.0.3',
    info: {
      title: `${repoName} API Documentation`,
      version: '1.0.0',
      description: `Automated OpenAPI specification generated by CDGS.`,
    },
    paths,
  }

  const content = JSON.stringify(openApiSpec, null, 2)

  return {
    filePath: 'docs/swagger.json',
    docType: 'api',
    title: 'OpenAPI Specification',
    content,
    contentHash: computeContentHash(content),
  }
}
