import type { UniversalCodeModel } from '../ucm.types'
import type { GeneratedDocument } from '../docgen.types'
import { computeContentHash } from '../parser.service'

/**
 * Generates Frontend Component Documentation (`docs/components.md`).
 */
export function generateComponentsDoc(ucm: UniversalCodeModel): GeneratedDocument | null {
  const components = ucm.entities.filter((e) => e.kind === 'component' || e.kind === 'hook')
  if (components.length === 0) return null

  const lines: string[] = [
    `# ${ucm.metadata.repoName} — Frontend Component Reference`,
    '',
    `Total Extracted UI Components & Hooks: **${components.length}**`,
    '',
    '---',
    '',
  ]

  for (const comp of components) {
    lines.push(
      `### Component: \`${comp.name}\``,
      '',
      `**Type**: \`${comp.kind}\` | **Source**: \`${comp.filePath}\`${comp.startLine ? ` (Line ${comp.startLine})` : ''}`,
      '',
      `**Purpose**: ${comp.description || `Frontend UI component rendering view components.`}`,
      '',
    )

    if (comp.parameters && comp.parameters.length > 0) {
      lines.push(
        '#### Props & Parameters',
        '',
        '| Prop Name | Type | Description |',
        '|---|---|---|',
      )
      for (const p of comp.parameters) {
        lines.push(`| \`${p.name}\` | \`${p.type || 'any'}\` | Prop \`${p.name}\` passed to component. |`)
      }
      lines.push('')
    }

    if (comp.fields && comp.fields.length > 0) {
      lines.push(
        '#### State & Component Properties',
        '',
        '| Property Name | Type |',
        '|---|---|',
      )
      for (const f of comp.fields) {
        lines.push(`| \`${f.name}\` | \`${f.type || 'any'}\` |`)
      }
      lines.push('')
    }

    lines.push('---', '')
  }

  lines.push('*Generated by CDGS Frontend Component Analyzer.*')

  const content = lines.join('\n')

  return {
    filePath: 'docs/components.md',
    docType: 'other',
    title: 'Frontend Component Reference',
    content,
    contentHash: computeContentHash(content),
  }
}
