import type { UniversalCodeModel } from '../ucm.types'
import type { GeneratedDocument } from '../docgen.types'
import { computeContentHash } from '../parser.service'
import { generateAIDatabaseData } from '../ai/database.ai'

/**
 * Generates Relational Database & Entity Relationship Documentation (`docs/database.md`).
 * Static analysis determines schemas & ER diagrams; OpenAI enriches semantic explanations.
 */
export async function generateDatabaseDoc(ucm: UniversalCodeModel): Promise<GeneratedDocument | null> {
  if (ucm.databaseTables.length === 0) return null

  const aiDbRes = await generateAIDatabaseData(ucm.databaseTables)
  const aiData = aiDbRes.data

  const lines: string[] = [
    `# ${ucm.metadata.repoName} — Database Reference & ER Diagram`,
    '',
    `Total Discovered Database Tables / Entities: **${ucm.databaseTables.length}**`,
    '',
    '---',
    '',
    '## 1. Database Overview',
    '',
    aiData?.overview || `Relational and entity data schemas detected across ${ucm.databaseTables.length} tables in \`${ucm.metadata.repoName}\`.`,
    '',
    '## 2. Entity Relationship (ER) Diagram',
    '',
    '```mermaid',
    'erDiagram',
  ]

  // Build ER Diagram Relationships strictly from static analysis
  const allRelationships: string[] = []
  for (const table of ucm.databaseTables) {
    if (table.relationships && table.relationships.length > 0) {
      for (const rel of table.relationships) {
        const conn = rel.type === 'one-to-many' ? '||--|{' : rel.type === 'many-to-many' ? '}|--|{' : '||--||'
        allRelationships.push(`    ${table.tableName} ${conn} ${rel.targetTable} : "references"`)
      }
    } else {
      lines.push(`    ${table.tableName} {`)
      for (const col of table.columns.slice(0, 8)) {
        const pkMarker = col.isPrimaryKey ? 'PK' : col.isForeignKey ? 'FK' : ''
        lines.push(`        ${col.type} ${col.name} ${pkMarker}`)
      }
      lines.push('    }')
    }
  }

  if (allRelationships.length > 0) {
    lines.push(...allRelationships)
  }

  lines.push(
    '```',
    '',
    '---',
    '',
    '## 3. Data Lifecycle & Entity Relationships Explanation',
    '',
    aiData?.dataLifecycle || 'Data entities undergo creation during application transactions, referencing primary/foreign key relationships across domain schema boundary models.',
    '',
  )

  if (aiData?.relationshipExplanations && aiData.relationshipExplanations.length > 0) {
    lines.push('### Relationship Details', '')
    for (const relExp of aiData.relationshipExplanations) {
      lines.push(`- ${relExp}`)
    }
    lines.push('')
  }

  lines.push(
    '## 4. Application-to-Database Entity Mapping',
    '',
    '| Service / Handler | Target Table | Primary Operation | Source File |',
    '|---|---|---|---|',
  )

  for (const table of ucm.databaseTables) {
    const matchingService = ucm.entities.find((e) =>
      e.name.toLowerCase().includes(table.tableName.toLowerCase()) ||
      table.tableName.toLowerCase().includes(e.name.toLowerCase())
    )
    const serviceName = matchingService ? matchingService.name : 'Domain Data Service'
    const file = matchingService ? matchingService.filePath : table.filePath

    lines.push(`| \`${serviceName}\` | \`${table.tableName}\` | \`PERSISTS / QUERY\` | \`${file}\` |`)
  }

  lines.push(
    '',
    '---',
    '',
    '## 5. Table Schema Specifications',
    '',
  )

  for (const table of ucm.databaseTables) {
    const purpose = aiData?.entityPurposes?.[table.tableName] || 'Not available from repository analysis.'

    lines.push(
      `### Table: \`${table.tableName}\``,
      '',
      `**Entity Purpose**: ${purpose}`,
      '',
      `Source Schema File: \`${table.filePath}\``,
      '',
      '| Column Name | Type | Key | Nullable | Description |',
      '|---|---|---|---|---|',
    )

    for (const col of table.columns) {
      const keyStr = col.isPrimaryKey ? '🔑 PK' : col.isForeignKey ? '🔗 FK' : '-'
      lines.push(`| \`${col.name}\` | \`${col.type}\` | ${keyStr} | ${col.isNullable ? 'Yes' : 'No'} | ${col.description || '-'} |`)
    }

    lines.push('', '---', '')
  }

  lines.push('*Generated by CDGS Database & Relationship Engine.*')

  const content = lines.join('\n')

  return {
    filePath: 'docs/database.md',
    docType: 'database',
    title: 'Database Reference & ER Diagram',
    content,
    contentHash: computeContentHash(content),
    aiModel: aiDbRes.modelUsed,
    tokenCount: aiDbRes.tokensUsed,
  }
}
