import type { UniversalCodeModel } from '../ucm.types'
import type { GeneratedDocument } from '../docgen.types'
import { computeContentHash } from '../parser.service'

/**
 * Generates Containerization & Deployment Documentation (`docs/deployment.md`).
 * Only generated if Dockerfile, Compose, Kubernetes, CI/CD, or IaC manifests exist.
 */
export function generateDeploymentDoc(ucm: UniversalCodeModel): GeneratedDocument | null {
  const meta = ucm.metadata
  if (!meta.hasDocker && !meta.configFiles.some((f) => f.includes('docker') || f.includes('k8s') || f.includes('terraform') || f.includes('workflow'))) {
    return null
  }

  const hasDockerfile = meta.configFiles.some((f) => f.toLowerCase().includes('dockerfile'))
  const hasCompose = meta.configFiles.some((f) => f.toLowerCase().includes('docker-compose') || f.toLowerCase().includes('compose.yml'))
  const hasK8s = meta.configFiles.some((f) => f.toLowerCase().includes('k8s') || f.toLowerCase().includes('helm') || f.endsWith('.yaml'))
  const hasCI = meta.configFiles.some((f) => f.includes('.github') || f.includes('jenkins') || f.includes('gitlab'))

  const lines: string[] = [
    `# ${meta.repoName} — Containerization & Deployment Guide`,
    '',
    `> **Production Infrastructure & Deployment Guide** verified for \`${meta.repoName}\`.`,
    '',
    '---',
    '',
    '## 1. Detected Infrastructure Manifests',
    '',
    `- **Docker Image Containerization**: ${hasDockerfile ? '✅ Dockerfile present' : 'Not detected'}`,
    `- **Multi-Container Compose**: ${hasCompose ? '✅ docker-compose configuration present' : 'Not detected'}`,
    `- **Kubernetes / IaC Manifests**: ${hasK8s ? '✅ Configured' : 'Not detected'}`,
    `- **CI/CD Pipelines**: ${hasCI ? '✅ Automation Workflows Detected' : 'Not detected'}`,
    '',
  ]

  if (hasDockerfile) {
    lines.push(
      '## 2. Docker Container Build & Run',
      '',
      '```bash',
      '# Build container image',
      `docker build -t ${meta.repoName.toLowerCase()}:latest .`,
      '',
      '# Run container instance',
      `docker run -d -p 8080:8080 ${meta.repoName.toLowerCase()}:latest`,
      '```',
      '',
    )
  }

  if (hasCompose) {
    lines.push(
      '## 3. Multi-Container Orchestration (Docker Compose)',
      '',
      '```bash',
      '# Start stack in background',
      'docker compose up -d',
      '',
      '# View service logs',
      'docker compose logs -f',
      '',
      '# Stop stack',
      'docker compose down',
      '```',
      '',
    )
  }

  lines.push(
    '---',
    '*Generated by CDGS Infrastructure & Deployment Analyzer.*',
  )

  const content = lines.join('\n')

  return {
    filePath: 'docs/deployment.md',
    docType: 'other',
    title: 'Containerization & Deployment Guide',
    content,
    contentHash: computeContentHash(content),
  }
}
