import type { UniversalCodeModel } from '../ucm.types'
import type { GeneratedDocument } from '../docgen.types'
import { computeContentHash } from '../parser.service'

/**
 * Generates Verified Getting Started & Environment Configuration Reference (`docs/getting_started.md`).
 * Does NOT assume or fabricate run commands unless verified from repository configuration manifests.
 */
export function generateGettingStartedDoc(ucm: UniversalCodeModel): GeneratedDocument {
  const meta = ucm.metadata
  const lines: string[] = [
    `# ${meta.repoName} — Getting Started & Developer Setup Guide`,
    '',
    `> **Developer Setup & Environment Guide** automatically verified for \`${meta.repoName}\`.`,
    '',
    '---',
    '',
    '## 1. Prerequisites',
    '',
    `- **Primary Runtime**: \`${meta.primaryLanguage}\``,
  ]

  if (meta.frameworks.length > 0) {
    lines.push(`- **Frameworks & Tooling**: ${meta.frameworks.map((f) => `\`${f}\``).join(', ')}`)
  }

  if (meta.hasDocker) {
    lines.push('- **Containerization**: Docker Engine & Docker Compose')
  }

  lines.push(
    '',
    '## 2. Environment Variables & Configuration',
    '',
  )

  if (meta.envVars && meta.envVars.length > 0) {
    lines.push(
      'The following environment variables were explicitly detected across repository configuration files. Secret values are masked.',
      '',
      '| Variable Name | Security Type | Sample / Default | Description |',
      '|---|---|---|---|',
    )
    for (const v of meta.envVars) {
      const typeStr = v.isSecret ? '🔒 Secret Key' : 'Configuration'
      const valStr = v.isSecret ? '`***MASKED***`' : `\`${v.sampleValue}\``
      lines.push(`| \`${v.name}\` | ${typeStr} | ${valStr} | Environment configuration parameter \`${v.name}\`. |`)
    }
    lines.push('')
  } else {
    lines.push('No custom environment variable declarations were explicitly detected in repository manifests.', '')
  }

  lines.push(
    '## 3. Installation & Local Execution',
    '',
    'Run the following verified commands in sequence to clone and execute the application:',
    '',
    '```bash',
    `# 1. Clone repository`,
    `git clone <repository_url>`,
    `cd ${meta.repoName}`,
    '',
  )

  if (meta.runCommands && meta.runCommands.length > 0) {
    lines.push('# 2. Verified execution commands from repository manifests:')
    for (const cmd of meta.runCommands) {
      lines.push(cmd)
    }
  } else {
    lines.push('# Execution commands not explicitly declared in manifest files (package.json, Makefile, pom.xml, etc.).')
    lines.push('# Please consult project owner or specific entrypoint scripts.')
  }

  lines.push(
    '```',
    '',
    '---',
    '*Generated by CDGS Developer Setup Analyzer.*',
  )

  const content = lines.join('\n')

  return {
    filePath: 'docs/getting_started.md',
    docType: 'other',
    title: 'Getting Started & Setup Guide',
    content,
    contentHash: computeContentHash(content),
  }
}
