import type { UniversalCodeModel, UCMEntity } from '../ucm.types'
import type { GeneratedDocument } from '../docgen.types'
import { computeContentHash } from '../parser.service'
import { generateAIModuleData } from '../ai/module.ai'

/**
 * Generates Professional Semantic Module & Code Reference (`docs/modules.md`).
 * Removes hardcoded generic boilerplate descriptions; uses OpenAI semantic explanations
 * or evidence-based fallbacks.
 */
export async function generateModulesDoc(ucm: UniversalCodeModel): Promise<GeneratedDocument> {
  let totalTokensUsed = 0
  let primaryModelUsed = 'deterministic-ast-engine'

  const lines: string[] = [
    `# ${ucm.metadata.repoName} — Code Module Reference`,
    '',
    `Total Extracted Code Entities & Symbols: **${ucm.entities.length}**`,
    '',
    '---',
    '',
  ]

  // Group entities by file path
  const fileMap = new Map<string, UCMEntity[]>()
  for (const entity of ucm.entities) {
    const list = fileMap.get(entity.filePath) || []
    list.push(entity)
    fileMap.set(entity.filePath, list)
  }

  for (const [file, entities] of fileMap.entries()) {
    // Generate AI explanation per module file
    const aiModuleRes = await generateAIModuleData(file, entities)
    if (aiModuleRes.tokensUsed > 0) {
      totalTokensUsed += aiModuleRes.tokensUsed
      primaryModelUsed = aiModuleRes.modelUsed
    }

    const aiData = aiModuleRes.data

    lines.push(
      `## Module: \`${file}\``,
      '',
      `**Language**: \`${entities[0]?.language || 'unknown'}\` | **Total Symbols**: ${entities.length}`,
      '',
      '### Purpose',
      aiData?.purpose || (entities[0]?.description ? entities[0].description : 'Not available from repository analysis.'),
      '',
    )

    if (aiData?.responsibilities && aiData.responsibilities.length > 0) {
      lines.push('### Responsibilities', '')
      for (const resp of aiData.responsibilities) {
        lines.push(`- ${resp}`)
      }
      lines.push('')
    }

    const classes = entities.filter((e) => ['class', 'model', 'entity', 'interface', 'struct', 'schema', 'controller', 'service'].includes(e.kind))
    const functions = entities.filter((e) => ['function', 'method', 'hook', 'component'].includes(e.kind))

    if (classes.length > 0) {
      lines.push(
        '### Classes & Data Models',
        '',
        '| Name | Kind | Line Range | Description |',
        '|---|---|---|---|',
      )
      for (const c of classes) {
        const lineStr = c.startLine ? (c.endLine ? `L${c.startLine}-L${c.endLine}` : `L${c.startLine}`) : '-'
        const desc = aiData?.symbolExplanations?.[c.name] || c.description || 'Not available from repository analysis.'
        lines.push(`| \`${c.name}\` | \`${c.kind}\` | ${lineStr} | ${desc} |`)
      }
      lines.push('')
    }

    if (functions.length > 0) {
      lines.push('### Functions & Methods Detailed Specification', '')
      for (const f of functions) {
        const paramsStr = f.parameters && f.parameters.length > 0
          ? f.parameters.map((p) => `\`${p.name}: ${p.type || 'any'}\``).join(', ')
          : 'None'
        const retStr = f.returnType ? `\`${f.returnType}\`` : '`void` / implicitly untyped'
        const lineRange = f.startLine ? (f.endLine ? `L${f.startLine}-L${f.endLine}` : `L${f.startLine}`) : 'L1'
        const desc = aiData?.symbolExplanations?.[f.name] || f.description || 'Not available from repository analysis.'

        // Related APIs matching function name or controller
        const relatedRoute = ucm.routes.find((r) => r.handlerName === f.name || r.controllerName === f.name)
        const relatedAPIStr = relatedRoute ? `\`${relatedRoute.method} ${relatedRoute.path}\`` : 'None'

        lines.push(
          `#### \`${f.name}()\``,
          '',
          `**Description**: ${desc}`,
          '',
          `- **Parameters**: ${paramsStr}`,
          `- **Returns**: ${retStr}`,
          `- **Calls**: ${f.calls && f.calls.length > 0 ? f.calls.map((c) => `\`${c}\``).join(', ') : 'None (terminal execution)'}`,
          `- **Used By**: ${f.usedBy && f.usedBy.length > 0 ? f.usedBy.map((u) => `\`${u}\``).join(', ') : 'None / Entry point'}`,
          `- **Database Tables**: ${f.relatedDatabaseTables && f.relatedDatabaseTables.length > 0 ? f.relatedDatabaseTables.map((t) => `\`${t}\``).join(', ') : 'None'}`,
          `- **Related APIs**: ${relatedAPIStr}`,
          `- **Source**: \`${file}:${lineRange}\``,
          '',
        )
      }
    }

    lines.push('---', '')
  }

  lines.push('*Generated by CDGS Semantic Code Reference Engine.*')

  const content = lines.join('\n')

  return {
    filePath: 'docs/modules.md',
    docType: 'module',
    title: 'Module & Code Reference',
    content,
    contentHash: computeContentHash(content),
    aiModel: primaryModelUsed,
    tokenCount: totalTokensUsed,
  }
}
