import type { UniversalCodeModel } from '../ucm.types'
import type { GeneratedDocument } from '../docgen.types'
import { computeContentHash } from '../parser.service'

/**
 * Generates Testing Strategy & Execution Guide (`docs/testing.md`).
 * Only generated if test files, test frameworks, or test scripts are explicitly detected.
 */
export function generateTestingDoc(ucm: UniversalCodeModel): GeneratedDocument | null {
  const meta = ucm.metadata
  if (!meta.hasTests && !meta.testFramework) return null

  const lines: string[] = [
    `# ${meta.repoName} — Testing Documentation & Strategy`,
    '',
    `> **Automated Test Suite Guide** verified for \`${meta.repoName}\`.`,
    '',
    '---',
    '',
    '## 1. Testing Frameworks & Setup',
    '',
    `- **Test Suite Status**: ✅ Active`,
    `- **Test Framework**: \`${meta.testFramework || 'Unit & Integration Suite'}\``,
    `- **Primary Language**: \`${meta.primaryLanguage}\``,
    '',
    '## 2. Verified Test Commands',
    '',
    'Run tests locally using verified commands detected from repository configuration:',
    '',
    '```bash',
  ]

  if (meta.testFramework === 'Vitest') {
    lines.push('npx vitest run')
  } else if (meta.testFramework === 'Jest') {
    lines.push('npx jest')
  } else if (meta.testFramework === 'PyTest') {
    lines.push('pytest')
  } else if (meta.testFramework === 'JUnit') {
    lines.push('mvn test')
  } else {
    lines.push('# Run test suite as configured in repository')
    if (meta.runCommands.some((c) => c.includes('test'))) {
      const testCmd = meta.runCommands.find((c) => c.includes('test'))
      if (testCmd) lines.push(testCmd)
    } else {
      lines.push('Not available from repository analysis.')
    }
  }

  lines.push(
    '```',
    '',
    '---',
    '*Generated by CDGS Testing Analyzer.*',
  )

  const content = lines.join('\n')

  return {
    filePath: 'docs/testing.md',
    docType: 'other',
    title: 'Testing Strategy & Test Commands',
    content,
    contentHash: computeContentHash(content),
  }
}
